# Generated by Django 6.1 on 2026-08-29 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_classify_existing_technology_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('retrieved_at', models.DateField()),
                ('download_url', models.URLField(blank=True)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('homepage_url', models.URLField(blank=True)),
                ('licence_name', models.CharField(blank=True, max_length=255)),
                ('licence_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('required_level_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('required_proficiency', models.CharField(blank=True, choices=[('foundational', 'Foundational'), ('developing', 'Developing'), ('proficient', 'Proficient'), ('advanced', 'Advanced')], max_length=20)),
                ('requirement_type', models.CharField(choices=[('essential', 'Essential'), ('optional', 'Optional'), ('unspecified', 'Unspecified')], default='unspecified', max_length=20)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_skills', to='careers.career')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='career_skills', to='profiles.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CareerSkillEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_occupation_id', models.CharField(blank=True, max_length=255)),
                ('external_skill_id', models.CharField(blank=True, max_length=255)),
                ('source_domain', models.CharField(blank=True, max_length=100)),
                ('source_relation', models.CharField(blank=True, max_length=100)),
                ('raw_importance', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('normalized_importance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('raw_level', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('normalized_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('scale_minimum', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('scale_maximum', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('not_relevant', models.BooleanField(default=False)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='careers.careerskill')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='career_skill_evidence', to='careers.referencedataset')),
            ],
        ),
        migrations.CreateModel(
            name='CareerExternalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('external_title', models.CharField(max_length=255)),
                ('mapping_method', models.CharField(choices=[('exact_code', 'Exact Code'), ('official_crosswalk', 'Official Crosswalk'), ('exact_title', 'Exact Title'), ('normalized_title', 'Normalized Title'), ('manual', 'Manual')], max_length=30)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to='careers.career')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='career_mappings', to='careers.referencedataset')),
            ],
        ),
        migrations.AddField(
            model_name='referencedataset',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='careers.referencesource'),
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='profiles.skill')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skill_aliases', to='careers.referencesource')),
            ],
        ),
        migrations.CreateModel(
            name='SkillExternalMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('external_label', models.CharField(max_length=255)),
                ('source_domain', models.CharField(blank=True, max_length=100)),
                ('mapping_method', models.CharField(choices=[('exact_code', 'Exact Code'), ('official_crosswalk', 'Official Crosswalk'), ('exact_title', 'Exact Title'), ('normalized_title', 'Normalized Title'), ('manual', 'Manual')], max_length=30)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_mappings', to='careers.referencedataset')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to='profiles.skill')),
            ],
        ),
        migrations.AddConstraint(
            model_name='careerskill',
            constraint=models.UniqueConstraint(fields=('career', 'skill'), name='unique_career_skill'),
        ),
        migrations.AddConstraint(
            model_name='careerskill',
            constraint=models.CheckConstraint(condition=models.Q(('importance_score__isnull', True), models.Q(('importance_score__gte', 0), ('importance_score__lte', 100)), _connector='OR'), name='valid_career_skill_importance'),
        ),
        migrations.AddConstraint(
            model_name='careerskill',
            constraint=models.CheckConstraint(condition=models.Q(('required_proficiency', ''), ('required_proficiency__in', ['foundational', 'developing', 'proficient', 'advanced']), _connector='OR'), name='valid_career_skill_proficiency'),
        ),
        migrations.AddConstraint(
            model_name='careerskill',
            constraint=models.CheckConstraint(condition=models.Q(('required_level_score__isnull', True), models.Q(('required_level_score__gte', 0), ('required_level_score__lte', 100)), _connector='OR'), name='valid_career_skill_required_level'),
        ),
        migrations.AddConstraint(
            model_name='careerskill',
            constraint=models.CheckConstraint(condition=models.Q(('requirement_type__in', ['essential', 'optional', 'unspecified'])), name='valid_career_skill_requirement_type'),
        ),
        migrations.AddConstraint(
            model_name='careerskill',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['pending', 'approved', 'rejected'])), name='valid_career_skill_review_status'),
        ),
        migrations.AddConstraint(
            model_name='careerskillevidence',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_importance__isnull', True), models.Q(('normalized_importance__gte', 0), ('normalized_importance__lte', 100)), _connector='OR'), name='valid_evidence_normalized_importance'),
        ),
        migrations.AddConstraint(
            model_name='careerskillevidence',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_level__isnull', True), models.Q(('normalized_level__gte', 0), ('normalized_level__lte', 100)), _connector='OR'), name='valid_evidence_normalized_level'),
        ),
        migrations.AddConstraint(
            model_name='careerskillevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scale_maximum__isnull', True), ('scale_minimum__isnull', True)), models.Q(('scale_maximum__gt', models.F('scale_minimum')), ('scale_maximum__isnull', False), ('scale_minimum__isnull', False)), _connector='OR'), name='valid_evidence_scale_range'),
        ),
        migrations.AddConstraint(
            model_name='careerskillevidence',
            constraint=models.UniqueConstraint(fields=('career_skill', 'dataset', 'external_occupation_id', 'external_skill_id', 'source_domain', 'source_relation'), name='unique_career_skill_evidence'),
        ),
        migrations.AddConstraint(
            model_name='careerexternalmapping',
            constraint=models.UniqueConstraint(fields=('career', 'dataset', 'external_id'), name='unique_career_external_mapping'),
        ),
        migrations.AddConstraint(
            model_name='careerexternalmapping',
            constraint=models.CheckConstraint(condition=models.Q(('mapping_method__in', ['exact_code', 'official_crosswalk', 'exact_title', 'normalized_title', 'manual'])), name='valid_career_mapping_method'),
        ),
        migrations.AddConstraint(
            model_name='careerexternalmapping',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['pending', 'approved', 'rejected'])), name='valid_career_mapping_review_status'),
        ),
        migrations.AddConstraint(
            model_name='careerexternalmapping',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__isnull', True), models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 100)), _connector='OR'), name='valid_career_mapping_confidence'),
        ),
        migrations.AddConstraint(
            model_name='referencedataset',
            constraint=models.UniqueConstraint(fields=('source', 'version'), name='unique_reference_source_version'),
        ),
        migrations.AddConstraint(
            model_name='referencedataset',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'superseded'])), name='valid_reference_dataset_status'),
        ),
        migrations.AddConstraint(
            model_name='skillalias',
            constraint=models.UniqueConstraint(fields=('skill', 'alias'), name='unique_skill_alias'),
        ),
        migrations.AddConstraint(
            model_name='skillexternalmapping',
            constraint=models.UniqueConstraint(fields=('dataset', 'external_id'), name='unique_external_skill_mapping'),
        ),
        migrations.AddConstraint(
            model_name='skillexternalmapping',
            constraint=models.CheckConstraint(condition=models.Q(('mapping_method__in', ['exact_code', 'official_crosswalk', 'exact_title', 'normalized_title', 'manual'])), name='valid_skill_mapping_method'),
        ),
        migrations.AddConstraint(
            model_name='skillexternalmapping',
            constraint=models.CheckConstraint(condition=models.Q(('review_status__in', ['pending', 'approved', 'rejected'])), name='valid_skill_mapping_review_status'),
        ),
        migrations.AddConstraint(
            model_name='skillexternalmapping',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__isnull', True), models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 100)), _connector='OR'), name='valid_skill_mapping_confidence'),
        ),
    ]
