# Generated by Django 6.1 on 2026-08-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerskillevidence',
            name='recommend_suppress',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
