# Generated by Django 6.1 on 2026-08-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_careerskillevidence_recommend_suppress'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='careerskillevidence',
            name='valid_evidence_scale_range',
        ),
        migrations.AddField(
            model_name='careerskillevidence',
            name='importance_scale_maximum',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='careerskillevidence',
            name='importance_scale_minimum',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='careerskillevidence',
            name='level_scale_maximum',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='careerskillevidence',
            name='level_scale_minimum',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='careerskillevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('importance_scale_maximum__isnull', True), ('importance_scale_minimum__isnull', True)), models.Q(('importance_scale_maximum__gt', models.F('importance_scale_minimum')), ('importance_scale_maximum__isnull', False), ('importance_scale_minimum__isnull', False)), _connector='OR'), name='valid_evidence_importance_scale_range'),
        ),
        migrations.AddConstraint(
            model_name='careerskillevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level_scale_maximum__isnull', True), ('level_scale_minimum__isnull', True)), models.Q(('level_scale_maximum__gt', models.F('level_scale_minimum')), ('level_scale_maximum__isnull', False), ('level_scale_minimum__isnull', False)), _connector='OR'), name='valid_evidence_level_scale_range'),
        ),
        migrations.RemoveField(
            model_name='careerskillevidence',
            name='scale_maximum',
        ),
        migrations.RemoveField(
            model_name='careerskillevidence',
            name='scale_minimum',
        ),
    ]
