# Generated by Django 6.1 on 2026-09-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_remove_careerskillevidence_valid_evidence_scale_range_and_more'),
        ('profiles', '0003_classify_existing_technology_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(unique=True)),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('documentation', 'Documentation'), ('article', 'Article'), ('video', 'Video'), ('tutorial', 'Tutorial'), ('book', 'Book'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResourceSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='careers.learningresource')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_resource_links', to='profiles.skill')),
            ],
        ),
        migrations.AddField(
            model_name='learningresource',
            name='skills',
            field=models.ManyToManyField(related_name='learning_resources', through='careers.LearningResourceSkill', to='profiles.skill'),
        ),
        migrations.AddConstraint(
            model_name='learningresourceskill',
            constraint=models.UniqueConstraint(fields=('learning_resource', 'skill'), name='unique_learning_resource_skill'),
        ),
        migrations.AddConstraint(
            model_name='learningresource',
            constraint=models.CheckConstraint(condition=models.Q(('resource_type__in', ['course', 'documentation', 'article', 'video', 'tutorial', 'book', 'other'])), name='valid_learning_resource_type'),
        ),
    ]
