# Generated by Codex on 2026-09-12

from django.db import migrations, models


CONTROLLED_RESOURCE_KEYS_BY_URL = {
    "https://docs.python.org/3/tutorial/": "python_tutorial",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide": (
        "javascript_guide"
    ),
    "https://git-scm.com/book/en/v2": "git_book",
    "https://www.postgresql.org/docs/current/tutorial-sql.html": (
        "postgresql_sql_tutorial"
    ),
}


def populate_resource_keys(apps, schema_editor):
    LearningResource = apps.get_model(
        "careers",
        "LearningResource",
    )

    used_keys = set()
    for resource in LearningResource.objects.order_by("id"):
        resource_key = CONTROLLED_RESOURCE_KEYS_BY_URL.get(
            resource.url
        )
        if resource_key is None:
            resource_key = (
                f"legacy_learning_resource_{resource.pk}"
            )

        if resource_key in used_keys:
            resource_key = (
                f"{resource_key[:100]}_{resource.pk}"
            )

        used_keys.add(resource_key)
        resource.resource_key = resource_key
        resource.save(
            update_fields=[
                "resource_key",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "careers",
            "0004_learningresource_learningresourceskill_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="resource_key",
            field=models.CharField(
                blank=True,
                max_length=120,
                null=True,
            ),
        ),
        migrations.RunPython(
            populate_resource_keys,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="learningresource",
            name="resource_key",
            field=models.CharField(
                max_length=120,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="learningresource",
            name="url",
            field=models.URLField(),
        ),
    ]
