# Generated by Django 6.1 on 2026-09-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_learningresource_resource_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerskillevidence',
            name='hot_technology',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerskillevidence',
            name='in_demand',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
