# Generated by Django 6.1 on 2026-09-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_careerskillevidence_hot_technology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerskillevidence',
            name='in_demand_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='careerskillevidence',
            constraint=models.CheckConstraint(condition=models.Q(('in_demand_percentage__isnull', True), models.Q(('in_demand_percentage__gte', 0), ('in_demand_percentage__lte', 100)), _connector='OR'), name='valid_evidence_in_demand_percentage'),
        ),
        migrations.AddConstraint(
            model_name='careerskillevidence',
            constraint=models.CheckConstraint(condition=models.Q(('in_demand_percentage__isnull', True), ('in_demand', True), _connector='OR'), name='evidence_percentage_requires_in_demand'),
        ),
    ]
