# Generated by Django 6.1 on 2026-09-16 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_careerskillevidence_in_demand_percentage_and_more'),
        ('profiles', '0003_classify_existing_technology_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_weight', models.PositiveSmallIntegerField()),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('source_type', models.CharField(choices=[('gradnavi_review', 'GradNavi Review'), ('external_evidence', 'External Evidence')], default='gradnavi_review', max_length=30)),
                ('source_reference', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_interests', to='careers.career')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='career_interests', to='profiles.interest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('career', 'interest'), name='unique_career_interest'), models.CheckConstraint(condition=models.Q(('relevance_weight__gte', 1), ('relevance_weight__lte', 5)), name='valid_career_interest_relevance'), models.CheckConstraint(condition=models.Q(('review_status__in', ['pending', 'approved', 'rejected'])), name='valid_career_interest_review_status'), models.CheckConstraint(condition=models.Q(('source_type__in', ['gradnavi_review', 'external_evidence'])), name='valid_career_interest_source_type')],
            },
        ),
        migrations.CreateModel(
            name='CareerRIASECProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realistic_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('investigative_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('artistic_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('social_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('enterprising_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conventional_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('source_reference', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riasec_profiles', to='careers.career')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='career_riasec_profiles', to='careers.referencedataset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('career', 'dataset'), name='unique_career_riasec_dataset'), models.CheckConstraint(condition=models.Q(('realistic_score__gte', 0), ('realistic_score__lte', 100)), name='valid_riasec_realistic_score'), models.CheckConstraint(condition=models.Q(('investigative_score__gte', 0), ('investigative_score__lte', 100)), name='valid_riasec_investigative_score'), models.CheckConstraint(condition=models.Q(('artistic_score__gte', 0), ('artistic_score__lte', 100)), name='valid_riasec_artistic_score'), models.CheckConstraint(condition=models.Q(('social_score__gte', 0), ('social_score__lte', 100)), name='valid_riasec_social_score'), models.CheckConstraint(condition=models.Q(('enterprising_score__gte', 0), ('enterprising_score__lte', 100)), name='valid_riasec_enterprising_score'), models.CheckConstraint(condition=models.Q(('conventional_score__gte', 0), ('conventional_score__lte', 100)), name='valid_riasec_conventional_score'), models.CheckConstraint(condition=models.Q(('review_status__in', ['pending', 'approved', 'rejected'])), name='valid_career_riasec_review_status')],
            },
        ),
    ]
