# Generated by Django 6.1 on 2026-09-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_careerinterest_careerriasecprofile'),
        ('profiles', '0005_backfill_career_goal_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_fingerprint', models.CharField(max_length=64)),
                ('reference_fingerprint', models.CharField(max_length=64)),
                ('scoring_version', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('career_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('student_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_snapshot', to='profiles.studentprofile')),
            ],
        ),
    ]
