# Generated by Django 6.1 on 2026-09-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0010_skillgapsummarysnapshot'),
        ('profiles', '0005_backfill_career_goal_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResourceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningResourceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('broken_link', 'Broken Link'), ('outdated', 'Outdated'), ('not_relevant', 'Not Relevant'), ('too_difficult', 'Too Difficult'), ('requires_payment', 'Requires Payment'), ('duplicate', 'Duplicate'), ('other', 'Other')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapGuidanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=64)),
                ('guidance_version', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField()),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='learningresource',
            name='access_type',
            field=models.CharField(choices=[('free', 'Free'), ('freemium', 'Freemium'), ('paid', 'Paid'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='health_status',
            field=models.CharField(choices=[('active', 'Active'), ('needs_review', 'Needs Review'), ('broken', 'Broken'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='source_type',
            field=models.CharField(choices=[('curated', 'Curated'), ('discovered', 'Discovered')], default='curated', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='learningresource',
            constraint=models.CheckConstraint(condition=models.Q(('access_type__in', ['free', 'freemium', 'paid', 'unknown'])), name='valid_learning_resource_access_type'),
        ),
        migrations.AddConstraint(
            model_name='learningresource',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['curated', 'discovered'])), name='valid_learning_resource_source_type'),
        ),
        migrations.AddConstraint(
            model_name='learningresource',
            constraint=models.CheckConstraint(condition=models.Q(('health_status__in', ['active', 'needs_review', 'broken', 'archived'])), name='valid_learning_resource_health_status'),
        ),
        migrations.AddField(
            model_name='learningresourcefeedback',
            name='learning_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback', to='careers.learningresource'),
        ),
        migrations.AddField(
            model_name='learningresourcefeedback',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resource_feedback', to='profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='learningresourcereport',
            name='learning_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='careers.learningresource'),
        ),
        migrations.AddField(
            model_name='learningresourcereport',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resource_reports', to='profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='roadmapguidancesnapshot',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_guidance_snapshots', to='careers.career'),
        ),
        migrations.AddField(
            model_name='roadmapguidancesnapshot',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_guidance_snapshots', to='profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='roadmapprogress',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_roadmap_progress', to='careers.career'),
        ),
        migrations.AddField(
            model_name='roadmapprogress',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_roadmap_progress', to='profiles.skill'),
        ),
        migrations.AddField(
            model_name='roadmapprogress',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_progress', to='profiles.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='learningresourcefeedback',
            constraint=models.UniqueConstraint(fields=('student_profile', 'learning_resource'), name='unique_student_learning_resource_feedback'),
        ),
        migrations.AddConstraint(
            model_name='learningresourcefeedback',
            constraint=models.CheckConstraint(condition=models.Q(('feedback_type__in', ['helpful', 'not_helpful'])), name='valid_learning_resource_feedback_type'),
        ),
        migrations.AddConstraint(
            model_name='learningresourcereport',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['broken_link', 'outdated', 'not_relevant', 'too_difficult', 'requires_payment', 'duplicate', 'other'])), name='valid_learning_resource_report_reason'),
        ),
        migrations.AddConstraint(
            model_name='learningresourcereport',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'resolved', 'dismissed'])), name='valid_learning_resource_report_status'),
        ),
        migrations.AddConstraint(
            model_name='roadmapguidancesnapshot',
            constraint=models.UniqueConstraint(fields=('student_profile', 'career'), name='unique_roadmap_guidance_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='roadmapprogress',
            constraint=models.UniqueConstraint(fields=('student_profile', 'career', 'skill'), name='unique_student_career_roadmap_skill'),
        ),
        migrations.AddConstraint(
            model_name='roadmapprogress',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['not_started', 'in_progress', 'completed'])), name='valid_roadmap_progress_status'),
        ),
    ]
