# Generated by Django 6.1 on 2026-09-18 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0011_learning_roadmap_enhancement_foundation'),
        ('profiles', '0005_backfill_career_goal_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResourceGuidanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=64)),
                ('guidance_version', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField()),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resource_guidance_snapshots', to='careers.career')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_resource_guidance_snapshots', to='profiles.skill')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resource_guidance_snapshots', to='profiles.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student_profile', 'career', 'skill'), name='unique_learning_resource_guidance_snapshot')],
            },
        ),
    ]
