# Generated by Django 6.1 on 2026-09-19 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0012_learning_resource_guidance_snapshot'),
        ('profiles', '0005_backfill_career_goal_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCareerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_fingerprint', models.CharField(max_length=64)),
                ('reference_fingerprint', models.CharField(max_length=64)),
                ('scoring_version', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_evaluations', to='careers.career')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_evaluations', to='profiles.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student_profile', 'career'), name='unique_student_career_evaluation')],
            },
        ),
    ]
