# Generated by Django 6.1 on 2026-09-19 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0013_studentcareerevaluation'),
        ('profiles', '0005_backfill_career_goal_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResourceDiscoveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('no_results', 'No Results'), ('provider_failure', 'Provider Failure')], max_length=30)),
                ('requested_count', models.PositiveSmallIntegerField()),
                ('candidate_count', models.PositiveSmallIntegerField(default=0)),
                ('persisted_count', models.PositiveSmallIntegerField(default=0)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('next_eligible_at', models.DateTimeField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_resource_discovery_attempts', to='profiles.skill')),
            ],
            options={
                'indexes': [models.Index(fields=['skill', '-attempted_at'], name='career_lrd_skill_attempt_idx'), models.Index(fields=['skill', 'next_eligible_at'], name='career_lrd_skill_next_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['success', 'partial', 'no_results', 'provider_failure'])), name='valid_learning_resource_discovery_status'), models.CheckConstraint(condition=models.Q(('requested_count__gte', 1), ('requested_count__lte', 6)), name='valid_learning_resource_discovery_request_count'), models.CheckConstraint(condition=models.Q(('candidate_count__lte', models.F('requested_count'))), name='learning_resource_discovery_candidates_lte_requested'), models.CheckConstraint(condition=models.Q(('persisted_count__lte', models.F('candidate_count'))), name='learning_resource_discovery_persisted_lte_candidates')],
            },
        ),
    ]
