# Generated by Django 6.1 on 2026-10-01 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=255)),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('questions_with_feedback', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-completed_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('total_questions__gte', 1), ('total_questions__lte', 10)), name='interview_session_total_questions_1_10'), models.CheckConstraint(condition=models.Q(('questions_with_feedback__gte', 0), ('questions_with_feedback__lte', models.F('total_questions'))), name='interview_session_feedback_lte_total')],
            },
        ),
    ]
