from django.urls import path

from .views import (
    AdminAnalyticsView,
    AdminAuditRecordDetailView,
    AdminAuditRecordListView,
    AdminCareerDetailView,
    AdminCareerListCreateView,
    AdminLearningResourceDetailView,
    AdminLearningResourceListCreateView,
    AdminLearningResourceReportDetailView,
    AdminLearningResourceReportListView,
    AdminSkillDetailView,
    AdminSkillListCreateView,
    AdminUserDetailView,
    AdminUserListView,
    AdminUserRoleUpdateView,
    AdminUserStatusUpdateView,
)


urlpatterns = [
    path(
        "analytics/",
        AdminAnalyticsView.as_view(),
        name="admin-analytics",
    ),
    path(
        "audit-records/",
        AdminAuditRecordListView.as_view(),
        name="admin-audit-record-list",
    ),
    path(
        "audit-records/<int:pk>/",
        AdminAuditRecordDetailView.as_view(),
        name="admin-audit-record-detail",
    ),
    path(
        "users/",
        AdminUserListView.as_view(),
        name="admin-user-list",
    ),
    path(
        "users/<int:pk>/",
        AdminUserDetailView.as_view(),
        name="admin-user-detail",
    ),
    path(
        "users/<int:pk>/role/",
        AdminUserRoleUpdateView.as_view(),
        name="admin-user-role",
    ),
    path(
        "users/<int:pk>/status/",
        AdminUserStatusUpdateView.as_view(),
        name="admin-user-status",
    ),
    path(
        "careers/",
        AdminCareerListCreateView.as_view(),
        name="admin-career-list",
    ),
    path(
        "careers/<int:pk>/",
        AdminCareerDetailView.as_view(),
        name="admin-career-detail",
    ),
    path(
        "skills/",
        AdminSkillListCreateView.as_view(),
        name="admin-skill-list",
    ),
    path(
        "skills/<int:pk>/",
        AdminSkillDetailView.as_view(),
        name="admin-skill-detail",
    ),
    path(
        "learning-resources/",
        AdminLearningResourceListCreateView.as_view(),
        name="admin-learning-resource-list",
    ),
    path(
        "learning-resources/<int:pk>/",
        AdminLearningResourceDetailView.as_view(),
        name="admin-learning-resource-detail",
    ),
    path(
        "learning-resource-reports/",
        AdminLearningResourceReportListView.as_view(),
        name="admin-learning-resource-report-list",
    ),
    path(
        "learning-resource-reports/<int:pk>/",
        AdminLearningResourceReportDetailView.as_view(),
        name="admin-learning-resource-report-detail",
    ),
]
