# Generated by Django 6.1 on 2026-08-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='concept_type',
            field=models.CharField(choices=[('skill', 'Skill'), ('knowledge', 'Knowledge'), ('technology', 'Technology')], default='skill', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.CheckConstraint(condition=models.Q(('concept_type__in', ['skill', 'knowledge', 'technology'])), name='valid_skill_concept_type'),
        ),
    ]
