# Generated by Django 6.1 on 2026-09-16 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_careerinterest_careerriasecprofile'),
        ('profiles', '0003_classify_existing_technology_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='careergoal',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_career_goals', to='careers.career'),
        ),
        migrations.AddField(
            model_name='careergoal',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='careergoal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('student_profile',), name='unique_primary_career_goal_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='careergoal',
            constraint=models.UniqueConstraint(condition=models.Q(('career__isnull', False)), fields=('student_profile', 'career'), name='unique_profile_career_goal'),
        ),
    ]
